name: Pre-Commit

on:
  push:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run pre-commit script
        run: |
          output=$(python your_test_script.py)
          if [[ $output == "Success" ]]; then
            echo "Committing changes..."
            git add .
            git commit -m "Committing changes"
          else
            echo "Test failed. Fix the issues and try again."
            exit 1
          fi
